-- 0. Limpiar base de datos antes de empezar (opcional para re-ejecutar)
DROP TABLE IF EXISTS messages, service_images, services, locations, categories, profiles CASCADE;

-- 1. Crear tabla de perfiles
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  role TEXT CHECK (role IN ('cliente', 'prestador')) NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- Create categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES categories(id),
  icon TEXT
);

-- Create locations table
CREATE TABLE locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province TEXT NOT NULL,
  city TEXT NOT NULL,
  UNIQUE(province, city)
);

-- Create services table
CREATE TABLE services (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) NOT NULL,
  location_id BIGINT REFERENCES locations(id) NOT NULL,
  price_from DECIMAL,
  is_active BOOLEAN DEFAULT true,
  rating DECIMAL DEFAULT 0,
  review_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create service_images table
CREATE TABLE service_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  service_id UUID REFERENCES services(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create messages table
CREATE TABLE messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  service_id UUID REFERENCES services(id) ON DELETE SET NULL,
  sender_id UUID REFERENCES profiles(id) NOT NULL,
  receiver_id UUID REFERENCES profiles(id) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create service_areas table (Many-to-Many)
CREATE TABLE service_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id UUID REFERENCES services(id) ON DELETE CASCADE NOT NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE NOT NULL
);

-- Enable Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Policies for categories/locations (read-only for public)
CREATE POLICY "Categories are viewable by everyone" ON categories FOR SELECT USING (true);
CREATE POLICY "Locations are viewable by everyone" ON locations FOR SELECT USING (true);

-- Policies for services
CREATE POLICY "Services are viewable by everyone" ON services FOR SELECT USING (true);
CREATE POLICY "Users can create their own services" ON services FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own services" ON services FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own services" ON services FOR DELETE USING (auth.uid() = user_id);

-- Policies for service_images
CREATE POLICY "Service images are viewable by everyone" ON service_images FOR SELECT USING (true);
CREATE POLICY "Users can manage images of their own services" ON service_images 
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM services 
      WHERE services.id = service_images.service_id 
      AND services.user_id = auth.uid()
    )
  );

-- Policies for messages
CREATE POLICY "Users can view messages they sent or received" ON messages 
  FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can send messages" ON messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- Policies for service_areas
ALTER TABLE service_areas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service areas are viewable by everyone" ON service_areas FOR SELECT USING (true);
CREATE POLICY "Users can manage areas of own services" ON service_areas 
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM services 
      WHERE services.id = service_areas.service_id 
      AND services.user_id = auth.uid()
    )
  );

-- Seed Categories
INSERT INTO categories (name, slug) VALUES 
('Aire acondicionado', 'aire-acondicionado'),
('Instalación de TV', 'instalacion-tv'),
('Electricidad', 'electricidad'),
('Plomería', 'plomeria'),
('Albañilería', 'albanileria'),
('Gas', 'gas'),
('Carpintería', 'carpinteria'),
('Herrería', 'herreria'),
('Pintura', 'pintura'),
('Limpieza', 'limpieza'),
('Jardinería', 'jardineria'),
('Informática', 'informatica'),
('Diseño gráfico', 'diseno-grafico'),
('Marketing', 'marketing'),
('Redes sociales', 'redes-sociales'),
('Soporte técnico', 'soporte-tecnico'),
('Impresiones 3D', 'impresiones-3d'),
('Mecánica de Autos', 'mecanica-autos'),
('Mecánica de Motos', 'mecanica-motos'),
('Cerrajería', 'cerrajeria'),
('Fletes y Mudanzas', 'fletes-mudanzas'),
('Reparación de Electrodomésticos', 'reparacion-electrodomesticos'),
('Mascotas', 'mascotas');

-- Seed Locations (Argentina)
INSERT INTO locations (province, city) VALUES 
('CABA', 'Agronomía'),
('CABA', 'Almagro'),
('CABA', 'Balvanera'),
('CABA', 'Barracas'),
('CABA', 'Belgrano'),
('CABA', 'Boedo'),
('CABA', 'Caballito'),
('CABA', 'Chacarita'),
('CABA', 'Coghlan'),
('CABA', 'Colegiales'),
('CABA', 'Constitución'),
('CABA', 'Flores'),
('CABA', 'Floresta'),
('CABA', 'La Boca'),
('CABA', 'Liniers'),
('CABA', 'Mataderos'),
('CABA', 'Monte Castro'),
('CABA', 'Monserrat'),
('CABA', 'Nueva Pompeya'),
('CABA', 'Núñez'),
('CABA', 'Palermo'),
('CABA', 'Parque Avellaneda'),
('CABA', 'Parque Chacabuco'),
('CABA', 'Parque Chas'),
('CABA', 'Parque Patricios'),
('CABA', 'Paternal'),
('CABA', 'Puerto Madero'),
('CABA', 'Recoleta'),
('CABA', 'Retiro'),
('CABA', 'Saavedra'),
('CABA', 'San Cristóbal'),
('CABA', 'San Nicolás (Microcentro)'),
('CABA', 'San Telmo'),
('CABA', 'Vélez Sarsfield'),
('CABA', 'Versalles'),
('CABA', 'Villa Crespo'),
('CABA', 'Villa del Parque'),
('CABA', 'Villa Devoto'),
('CABA', 'Villa General Mitre'),
('CABA', 'Villa Lugano'),
('CABA', 'Villa Luro'),
('CABA', 'Villa Ortúzar'),
('CABA', 'Villa Pueyrredón'),
('CABA', 'Villa Real'),
('CABA', 'Villa Riachuelo'),
('CABA', 'Villa Santa Rita'),
('CABA', 'Villa Soldati'),
('CABA', 'Villa Urquiza'),
('Buenos Aires/Norte', 'Vicente López'),
('Buenos Aires/Norte', 'Olivos'),
('Buenos Aires/Norte', 'Florida'),
('Buenos Aires/Norte', 'San Isidro'),
('Buenos Aires/Norte', 'Martínez'),
('Buenos Aires/Norte', 'Acassuso'),
('Buenos Aires/Norte', 'Beccar'),
('Buenos Aires/Norte', 'San Fernando'),
('Buenos Aires/Norte', 'Tigre'),
('Buenos Aires/Norte', 'General Pacheco'),
('Buenos Aires/Norte', 'Don Torcuato'),
('Buenos Aires/Norte', 'Benavídez'),
('Buenos Aires/Norte', 'Escobar'),
('Buenos Aires/Norte', 'Ingeniero Maschwitz'),
('Buenos Aires/Norte', 'Pilar'),
('Buenos Aires/Norte', 'Del Viso'),
('Buenos Aires/Norte', 'José C. Paz'),
('Buenos Aires/Oeste', 'Ramos Mejía'),
('Buenos Aires/Oeste', 'San Justo'),
('Buenos Aires/Oeste', 'La Matanza'),
('Buenos Aires/Oeste', 'Morón'),
('Buenos Aires/Oeste', 'Haedo'),
('Buenos Aires/Oeste', 'Castelar'),
('Buenos Aires/Oeste', 'Ituzaingó'),
('Buenos Aires/Oeste', 'Merlo'),
('Buenos Aires/Oeste', 'Moreno'),
('Buenos Aires/Oeste', 'Paso del Rey'),
('Buenos Aires/Oeste', 'Hurlingham'),
('Buenos Aires/Oeste', 'Tres de Febrero'),
('Buenos Aires/Oeste', 'Caseros'),
('Buenos Aires/Oeste', 'Ciudadela'),
('Buenos Aires/Oeste', 'El Palomar'),
('Buenos Aires/Sur', 'Avellaneda'),
('Buenos Aires/Sur', 'Lanús'),
('Buenos Aires/Sur', 'Gerli'),
('Buenos Aires/Sur', 'Remedios de Escalada'),
('Buenos Aires/Sur', 'Lomas de Zamora'),
('Buenos Aires/Sur', 'Banfield'),
('Buenos Aires/Sur', 'Temperley'),
('Buenos Aires/Sur', 'Adrogué'),
('Buenos Aires/Sur', 'Almirante Brown'),
('Buenos Aires/Sur', 'Quilmes'),
('Buenos Aires/Sur', 'Bernal'),
('Buenos Aires/Sur', 'Ezpeleta'),
('Buenos Aires/Sur', 'Florencio Varela'),
('Buenos Aires/Sur', 'Berazategui'),
('Buenos Aires/Sur', 'Wilde'),
('Buenos Aires/Sur', 'Dock Sud'),
('Córdoba', 'Córdoba Capital'),
('Santa Fe', 'Rosario'),
('Mendoza', 'Mendoza Capital')
-- Messaging System
CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    service_id UUID REFERENCES services(id) ON DELETE SET NULL,
    buyer_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    seller_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(service_id, buyer_id, seller_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL
);

-- RLS for Messaging
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see their own conversations" 
ON conversations FOR SELECT 
USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

CREATE POLICY "Users can create conversations" 
ON conversations FOR INSERT 
WITH CHECK (auth.uid() = buyer_id);

CREATE POLICY "Users can update their own conversations" 
ON conversations FOR UPDATE 
USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

CREATE POLICY "Users can insert messages in their conversations" 
ON messages FOR INSERT 
WITH CHECK (
    conversation_id IN (
        SELECT id FROM conversations 
        WHERE auth.uid() = buyer_id OR auth.uid() = seller_id
    )
);

CREATE POLICY "Users can see messages in their conversations" 
ON messages FOR SELECT 
USING (
    conversation_id IN (
        SELECT id FROM conversations 
        WHERE auth.uid() = buyer_id OR auth.uid() = seller_id
    )
);

CREATE POLICY "Users can mark messages as read" 
ON messages FOR UPDATE 
USING (
    conversation_id IN (
        SELECT id FROM conversations 
        WHERE auth.uid() = buyer_id OR auth.uid() = seller_id
    )
)
WITH CHECK (
    conversation_id IN (
        SELECT id FROM conversations 
        WHERE auth.uid() = buyer_id OR auth.uid() = seller_id
    )
);

-- Trigger to update conversation updated_at
CREATE OR REPLACE FUNCTION update_conversation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE conversations 
    SET updated_at = timezone('utc'::text, now())
    WHERE id = NEW.conversation_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_new_message
AFTER INSERT ON messages
FOR EACH ROW EXECUTE FUNCTION update_conversation_timestamp();

-- Service Hiring System
CREATE TYPE hire_status AS ENUM ('pending', 'accepted', 'rejected', 'completed', 'canceled');

CREATE TABLE IF NOT EXISTS hires (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    service_id UUID REFERENCES services(id) ON DELETE SET NULL,
    client_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    status hire_status DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for Hires
ALTER TABLE hires ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Clients can see their own hired services" 
ON hires FOR SELECT 
USING (auth.uid() = client_id);

CREATE POLICY "Providers can see their assigned jobs" 
ON hires FOR SELECT 
USING (auth.uid() = provider_id);

CREATE POLICY "Clients can request hires" 
ON hires FOR INSERT 
WITH CHECK (auth.uid() = client_id);

CREATE POLICY "Participants can update hire status" 
ON hires FOR UPDATE 
USING (auth.uid() = client_id OR auth.uid() = provider_id);

-- Trigger to update hire updated_at
CREATE OR REPLACE FUNCTION update_hire_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_hire_update
BEFORE UPDATE ON hires
FOR EACH ROW EXECUTE FUNCTION update_hire_timestamp();

-- Enable Realtime for these tables
ALTER PUBLICATION supabase_realtime ADD TABLE conversations;
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
ALTER PUBLICATION supabase_realtime ADD TABLE hires;

-- Service Rating System
CREATE TABLE IF NOT EXISTS reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    hire_id UUID REFERENCES hires(id) ON DELETE CASCADE UNIQUE,
    service_id UUID REFERENCES services(id) ON DELETE CASCADE,
    client_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for Reviews
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone" 
ON reviews FOR SELECT 
USING (true);

CREATE POLICY "Clients can review completed hires" 
ON reviews FOR INSERT 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM hires 
        WHERE id = hire_id 
        AND client_id = auth.uid() 
        AND status = 'completed'
    )
);

-- Trigger to update service rating stats
CREATE OR REPLACE FUNCTION update_service_rating_stats()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE services 
    SET 
        rating = (SELECT AVG(rating)::DECIMAL FROM reviews WHERE service_id = NEW.service_id),
        review_count = (SELECT COUNT(*)::INTEGER FROM reviews WHERE service_id = NEW.service_id)
    WHERE id = NEW.service_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_review_added
AFTER INSERT OR UPDATE OR DELETE ON reviews
FOR EACH ROW EXECUTE FUNCTION update_service_rating_stats();

-- Add reviews to real-time
ALTER PUBLICATION supabase_realtime ADD TABLE reviews;

-- Cleanup storage policies to avoid errors on re-run
DROP POLICY IF EXISTS "Permitir subida de fotos a usuarios autenticados" ON storage.objects;
DROP POLICY IF EXISTS "Permitir lectura pública de fotos" ON storage.objects;

-- Storage Policies
CREATE POLICY "Permitir subida de fotos a usuarios autenticados"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'service-images');

CREATE POLICY "Permitir lectura pública de fotos"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'service-images');

