-- ==============================================================================
-- ALTOQUE - ESQUEMA DE BASE DE DATOS FINAL Y LIMPIO
-- ==============================================================================

-- 1. TABLAS PRINCIPALES
-- ==============================================================================

-- Profiles (Perfiles de usuario)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  role TEXT CHECK (role IN ('cliente', 'prestador')) NOT NULL,
  full_name TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  phone TEXT,
  avatar_url TEXT,
  -- Campos de ubicación
  location_id BIGINT, -- Se crea relación más abajo después de crear tabla locations
  address TEXT,
  -- Campos de Negocio / Prestador
  business_name TEXT,
  legal_name TEXT,
  logo_url TEXT,
  website TEXT,
  social_media TEXT,
  business_hours TEXT,
  years_in_business INTEGER,
  -- Campos de Prestador Independiente
  provider_type TEXT DEFAULT 'independent', -- 'independent' or 'business'
  bio TEXT,
  work_mode TEXT DEFAULT 'solo', -- 'solo' or 'helper'
  -- Campos Legales
  cuit TEXT,
  fiscal_address TEXT,
  legal_docs_url TEXT,
  certificates_url TEXT,
  service_preferences TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Categories (Categorías de servicios)
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES categories(id),
  icon TEXT
);

-- Locations (Ubicaciones)
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province TEXT NOT NULL,
  city TEXT NOT NULL,
  UNIQUE(province, city)
);

-- Agregar la FK a profiles que quedó pendiente
ALTER TABLE profiles 
ADD CONSTRAINT fk_profiles_location 
FOREIGN KEY (location_id) REFERENCES locations(id);

-- Services (Servicios ofrecidos)
CREATE TABLE IF NOT EXISTS services (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) NOT NULL,
  location_id BIGINT REFERENCES locations(id) NOT NULL,
  price_from DECIMAL,
  is_active BOOLEAN DEFAULT true,
  rating DECIMAL DEFAULT 0,
  review_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Service Images (Imágenes de servicios)
CREATE TABLE IF NOT EXISTS service_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  service_id UUID REFERENCES services(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Service Areas (Áreas de cobertura - Muchos a Muchos)
CREATE TABLE IF NOT EXISTS service_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id UUID REFERENCES services(id) ON DELETE CASCADE NOT NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE NOT NULL
);


-- 2. SISTEMA DE MENSAJERÍA
-- ==============================================================================

CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    service_id UUID REFERENCES services(id) ON DELETE SET NULL,
    buyer_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    seller_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(service_id, buyer_id, seller_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL
);


-- 3. SISTEMA DE CONTRATACIONES Y RESEÑAS
-- ==============================================================================

CREATE TYPE hire_status AS ENUM ('pending', 'accepted', 'rejected', 'completed', 'canceled');

CREATE TABLE IF NOT EXISTS hires (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    service_id UUID REFERENCES services(id) ON DELETE SET NULL,
    client_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    status hire_status DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    hire_id UUID REFERENCES hires(id) ON DELETE CASCADE UNIQUE,
    service_id UUID REFERENCES services(id) ON DELETE CASCADE,
    client_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 4. FUNCIONES Y TRIGGERS
-- ==============================================================================

-- Trigger: Crear perfil automáticamente al registrar usuario
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (
    id, full_name, first_name, last_name, role, phone, location_id, provider_type, business_name, avatar_url
  )
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    COALESCE(new.raw_user_meta_data->>'role', 'cliente'),
    new.raw_user_meta_data->>'phone',
    (new.raw_user_meta_data->>'location_id')::bigint,
    new.raw_user_meta_data->>'provider_type',
    new.raw_user_meta_data->>'business_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: Actualizar timestamp de conversación
CREATE OR REPLACE FUNCTION update_conversation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE conversations SET updated_at = now() WHERE id = NEW.conversation_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_new_message
  AFTER INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION update_conversation_timestamp();

-- Trigger: Actualizar timestamp de contratación
CREATE OR REPLACE FUNCTION update_hire_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_hire_update
  BEFORE UPDATE ON hires
  FOR EACH ROW EXECUTE FUNCTION update_hire_timestamp();

-- Trigger: Actualizar estadísticas de calificación de servicio
CREATE OR REPLACE FUNCTION update_service_rating_stats()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE services 
    SET 
        rating = (SELECT AVG(rating)::DECIMAL FROM reviews WHERE service_id = NEW.service_id),
        review_count = (SELECT COUNT(*)::INTEGER FROM reviews WHERE service_id = NEW.service_id)
    WHERE id = NEW.service_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_review_added
  AFTER INSERT OR UPDATE OR DELETE ON reviews
  FOR EACH ROW EXECUTE FUNCTION update_service_rating_stats();


-- 5. SEGURIDAD (ROW LEVEL SECURITY - RLS)
-- ==============================================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE hires ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Políticas Profiles
CREATE POLICY "Public profiles viewable" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users handle own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Políticas Categories/Locations (Públicas)
CREATE POLICY "Categories viewable" ON categories FOR SELECT USING (true);
CREATE POLICY "Locations viewable" ON locations FOR SELECT USING (true);

-- Políticas Services
CREATE POLICY "Public services viewable" ON services FOR SELECT USING (true);
CREATE POLICY "Users handle own services" ON services FOR ALL USING (auth.uid() = user_id);

-- Políticas Service Images
CREATE POLICY "Service images viewable" ON service_images FOR SELECT USING (true);
CREATE POLICY "Users manage own images" ON service_images FOR ALL USING (
    EXISTS (SELECT 1 FROM services WHERE id = service_images.service_id AND user_id = auth.uid())
);

-- Políticas Service Areas
CREATE POLICY "Service areas viewable" ON service_areas FOR SELECT USING (true);
CREATE POLICY "Users manage own areas" ON service_areas FOR ALL USING (
    EXISTS (SELECT 1 FROM services WHERE id = service_areas.service_id AND user_id = auth.uid())
);

-- Políticas Mensajería
CREATE POLICY "Users view own conversations" ON conversations FOR SELECT 
USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

CREATE POLICY "Users create conversations" ON conversations FOR INSERT 
WITH CHECK (auth.uid() = buyer_id); -- Solo clientes inician?

CREATE POLICY "Users update own conversations" ON conversations FOR UPDATE 
USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

CREATE POLICY "Users view messages" ON messages FOR SELECT 
USING (EXISTS (SELECT 1 FROM conversations WHERE id = conversation_id AND (auth.uid() = buyer_id OR auth.uid() = seller_id)));

CREATE POLICY "Users send messages" ON messages FOR INSERT 
WITH CHECK (EXISTS (SELECT 1 FROM conversations WHERE id = conversation_id AND (auth.uid() = buyer_id OR auth.uid() = seller_id)));

CREATE POLICY "Users mark messages read" ON messages FOR UPDATE 
USING (EXISTS (SELECT 1 FROM conversations WHERE id = conversation_id AND (auth.uid() = buyer_id OR auth.uid() = seller_id)));

-- Políticas Contrataciones (Hires)
CREATE POLICY "Clients see own hires" ON hires FOR SELECT USING (auth.uid() = client_id);
CREATE POLICY "Providers see assigned jobs" ON hires FOR SELECT USING (auth.uid() = provider_id);
CREATE POLICY "Clients request hires" ON hires FOR INSERT WITH CHECK (auth.uid() = client_id);
CREATE POLICY "Participants update status" ON hires FOR UPDATE USING (auth.uid() = client_id OR auth.uid() = provider_id);

-- Políticas Reseñas (Reviews)
CREATE POLICY "Reviews viewable by everyone" ON reviews FOR SELECT USING (true);
CREATE POLICY "Clients review completed hires" ON reviews FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM hires WHERE id = hire_id AND client_id = auth.uid() AND status = 'completed')
);


-- 6. DATOS INICIALES (SEEDS)
-- ==============================================================================

-- Inserción de Categorías (con manejo de duplicados)
INSERT INTO categories (name, slug, icon) VALUES 
('Aire Acondicionado', 'aire-acondicionado', 'Wrench'),
('Electricidad', 'electricidad', 'Zap'),
('Plomería', 'plomeria', 'Droplets'),
('Pintura', 'pintura', 'PaintBucket'),
('Limpieza', 'limpieza', 'CheckCircle2'),
('Albañilería', 'albanileria', 'Hammer'),
('Gas', 'gas', 'Lightbulb'),
('Soporte Técnico', 'soporte-tecnico', 'Monitor'),
('Carpintería', 'carpinteria', 'Hammer'),
('Herrería', 'herreria', 'ShieldCheck'),
('Jardinería', 'jardineria', 'Scissors'),
('Informática', 'informatica', 'Monitor'),
('Diseño gráfico', 'diseno-grafico', 'Palette'),
('Marketing', 'marketing', 'Megaphone'),
('Redes sociales', 'redes-sociales', 'Share2'),
('Impresiones 3D', 'impresiones-3d', 'Box'),
('Render/Diseño 3D', 'render-diseno-3d', 'Box'),
('Mecánica de Autos', 'mecanica-autos', 'Car'),
('Mecánica de Motos', 'mecanica-motos', 'Bike'),
('Cerrajería', 'cerrajeria', 'Key'),
('Reparación de Electrodomésticos', 'reparacion-electrodomesticos', 'Tv'),
('Mascotas', 'mascotas', 'Dog'),
('Cadetería', 'cadeteria', 'HardHat'),
('Remis', 'remis', 'CarFront'),
('Fletes y Mudanzas', 'fletes-mudanzas', 'Truck')
ON CONFLICT (slug) DO UPDATE 
SET name = EXCLUDED.name, icon = EXCLUDED.icon;

-- Inserción de Ubicaciones (Ejemplo resumido)
INSERT INTO locations (province, city) VALUES 
('CABA', 'Almagro'), ('CABA', 'Palermo'), ('CABA', 'Villa Crespo'), 
('CABA', 'Belgrano'), ('CABA', 'Caballito'), ('CABA', 'Recoleta'),
('Buenos Aires/Norte', 'Vicente López'), ('Buenos Aires/Norte', 'San Isidro'),
('Buenos Aires/Oeste', 'Morón'), ('Buenos Aires/Oeste', 'Ramos Mejía'),
('Buenos Aires/Sur', 'Avellaneda'), ('Buenos Aires/Sur', 'Lanús'),
('Córdoba', 'Córdoba Capital'), ('Santa Fe', 'Rosario')
ON CONFLICT (province, city) DO NOTHING;
